# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

FistaLV <- function(Y, Z, B, gam, eps, tk, k, p) {
    .Call('BigVAR_FistaLV', PACKAGE = 'BigVAR', Y, Z, B, gam, eps, tk, k, p)
}

gamloopFista <- function(beta_, Y, Z, gamm, eps, YMean2, ZMean2, B1, k, p) {
    .Call('BigVAR_gamloopFista', PACKAGE = 'BigVAR', beta_, Y, Z, gamm, eps, YMean2, ZMean2, B1, k, p)
}

Eigencomp <- function(Z1, groups, n1, k) {
    .Call('BigVAR_Eigencomp', PACKAGE = 'BigVAR', Z1, groups, n1, k)
}

EigencompOO <- function(ZZ1, groups, n1, k) {
    .Call('BigVAR_EigencompOO', PACKAGE = 'BigVAR', ZZ1, groups, n1, k)
}

BlockUpdateGL <- function(beta, Z1, lam, Y1, eps, groups, fullgroups, compgroups, k, M3f_, eigvalF_, eigvecF_) {
    .Call('BigVAR_BlockUpdateGL', PACKAGE = 'BigVAR', beta, Z1, lam, Y1, eps, groups, fullgroups, compgroups, k, M3f_, eigvalF_, eigvecF_)
}

ThreshUpdate <- function(betaActive, Z1, lam, Y1, eps, groups, fullgroups, compgroups, M2f_, eigvalF_, eigvecF_) {
    .Call('BigVAR_ThreshUpdate', PACKAGE = 'BigVAR', betaActive, Z1, lam, Y1, eps, groups, fullgroups, compgroups, M2f_, eigvalF_, eigvecF_)
}

GamLoopGL <- function(beta_, Activeset, gamm, Y1, Z1, jj, jjfull, jjcomp, eps, YMean2, ZMean2, k, pk, M2f_, eigvalF_, eigvecF_) {
    .Call('BigVAR_GamLoopGL', PACKAGE = 'BigVAR', beta_, Activeset, gamm, Y1, Z1, jj, jjfull, jjcomp, eps, YMean2, ZMean2, k, pk, M2f_, eigvalF_, eigvecF_)
}

BlockUpdate2 <- function(ZZ1, lam, Y1, eps, groups, fullgroups, compgroups, k, M2f_, eigvalF_, eigvecF_, B) {
    .Call('BigVAR_BlockUpdate2', PACKAGE = 'BigVAR', ZZ1, lam, Y1, eps, groups, fullgroups, compgroups, k, M2f_, eigvalF_, eigvecF_, B)
}

ThreshUpdateOO <- function(ZZ, lam, Y, eps, groups, fullgroups, compgroups, M2f_, eigvalF_, eigvecF_, B, n) {
    .Call('BigVAR_ThreshUpdateOO', PACKAGE = 'BigVAR', ZZ, lam, Y, eps, groups, fullgroups, compgroups, M2f_, eigvalF_, eigvecF_, B, n)
}

GamLoopGLOO <- function(beta_, Activeset, gamm, Y, Z, jj, jjfull, jjcomp, eps, YMean2, ZMean2, k, pk, M2f_, eigvalF_, eigvecF_) {
    .Call('BigVAR_GamLoopGLOO', PACKAGE = 'BigVAR', beta_, Activeset, gamm, Y, Z, jj, jjfull, jjcomp, eps, YMean2, ZMean2, k, pk, M2f_, eigvalF_, eigvecF_)
}

GamLoopSGL <- function(beta_, Activeset, gamm, alpha, Y1, Z1, jj, jjfull, jjcomp, eps, YMean2, ZMean2, k, pk, M1f_, M2f_, eigs_) {
    .Call('BigVAR_GamLoopSGL', PACKAGE = 'BigVAR', beta_, Activeset, gamm, alpha, Y1, Z1, jj, jjfull, jjcomp, eps, YMean2, ZMean2, k, pk, M1f_, M2f_, eigs_)
}

sparseWLOO <- function(M1a, R1, ngroups, beta, t, alpha, lambda, eps, rho) {
    .Call('BigVAR_sparseWLOO', PACKAGE = 'BigVAR', M1a, R1, ngroups, beta, t, alpha, lambda, eps, rho)
}

GamLoopSGLOO <- function(beta_, Activeset_, gamm, alpha, Y, Z, jj_, jjfull_, jjcomp_, eps, YMean2, ZMean2, k, pk, M1f_, M2f_, eigs_) {
    .Call('BigVAR_GamLoopSGLOO', PACKAGE = 'BigVAR', beta_, Activeset_, gamm, alpha, Y, Z, jj_, jjfull_, jjcomp_, eps, YMean2, ZMean2, k, pk, M1f_, M2f_, eigs_)
}

powermethod <- function(A1, x1) {
    .Call('BigVAR_powermethod', PACKAGE = 'BigVAR', A1, x1)
}

norm2 <- function(x) {
    .Call('BigVAR_norm2', PACKAGE = 'BigVAR', x)
}

