# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ZmatF <- function(Y, p, k, intercept = TRUE, oos = FALSE, contemp = FALSE) {
    .Call('BigVAR_ZmatF', PACKAGE = 'BigVAR', Y, p, k, intercept, oos, contemp)
}

VARXCons <- function(Y, X, k, p, m, s, oos = FALSE, contemp = FALSE) {
    .Call('BigVAR_VARXCons', PACKAGE = 'BigVAR', Y, X, k, p, m, s, oos, contemp)
}

ST1a <- function(z, gam) {
    .Call('BigVAR_ST1a', PACKAGE = 'BigVAR', z, gam)
}

ST3a <- function(z, gam) {
    .Call('BigVAR_ST3a', PACKAGE = 'BigVAR', z, gam)
}

ST3bc <- function(z, gam) {
    .Call('BigVAR_ST3bc', PACKAGE = 'BigVAR', z, gam)
}

FistaLV <- function(Y, Z, B, gam, eps, tk, k, p) {
    .Call('BigVAR_FistaLV', PACKAGE = 'BigVAR', Y, Z, B, gam, eps, tk, k, p)
}

gamloopFista <- function(beta_, Y, Z, gammgrid, eps, YMean2, ZMean2, B1, k, p, tk, k1, s) {
    .Call('BigVAR_gamloopFista', PACKAGE = 'BigVAR', beta_, Y, Z, gammgrid, eps, YMean2, ZMean2, B1, k, p, tk, k1, s)
}

Eigencomp <- function(Z1, groups, n1, k1) {
    .Call('BigVAR_Eigencomp', PACKAGE = 'BigVAR', Z1, groups, n1, k1)
}

EigencompOO <- function(ZZ1, groups, n1, k) {
    .Call('BigVAR_EigencompOO', PACKAGE = 'BigVAR', ZZ1, groups, n1, k)
}

BlockUpdateGL <- function(beta, Z1, lam, Y1, eps, groups, fullgroups, compgroups, k, M3f_, eigvalF_, eigvecF_, k1) {
    .Call('BigVAR_BlockUpdateGL', PACKAGE = 'BigVAR', beta, Z1, lam, Y1, eps, groups, fullgroups, compgroups, k, M3f_, eigvalF_, eigvecF_, k1)
}

ThreshUpdate <- function(betaActive, Z1, lam, Y1, eps, groups, fullgroups, compgroups, M2f_, eigvalF_, eigvecF_, k1) {
    .Call('BigVAR_ThreshUpdate', PACKAGE = 'BigVAR', betaActive, Z1, lam, Y1, eps, groups, fullgroups, compgroups, M2f_, eigvalF_, eigvecF_, k1)
}

GamLoopGL2 <- function(beta_, Activeset, gamm, Y1, Z1, jj, jjfull, jjcomp, eps, YMean2, ZMean2, k, pk, M2f_, eigvalF_, eigvecF_) {
    .Call('BigVAR_GamLoopGL2', PACKAGE = 'BigVAR', beta_, Activeset, gamm, Y1, Z1, jj, jjfull, jjcomp, eps, YMean2, ZMean2, k, pk, M2f_, eigvalF_, eigvecF_)
}

GroupLassoVAR <- function(beta_, Y, Z, gamm, eps, k, p, INIActive_, jj, Compgroups, k1, s, MN) {
    .Call('BigVAR_GroupLassoVAR', PACKAGE = 'BigVAR', beta_, Y, Z, gamm, eps, k, p, INIActive_, jj, Compgroups, k1, s, MN)
}

BlockUpdate2 <- function(ZZ1, lam, Y1, eps, groups, fullgroups, compgroups, k, M2f_, eigvalF_, eigvecF_, B, k1) {
    .Call('BigVAR_BlockUpdate2', PACKAGE = 'BigVAR', ZZ1, lam, Y1, eps, groups, fullgroups, compgroups, k, M2f_, eigvalF_, eigvecF_, B, k1)
}

ThreshUpdateOO <- function(ZZ, lam, Y, eps, groups, fullgroups, compgroups, M2f_, eigvalF_, eigvecF_, B, n, k1) {
    .Call('BigVAR_ThreshUpdateOO', PACKAGE = 'BigVAR', ZZ, lam, Y, eps, groups, fullgroups, compgroups, M2f_, eigvalF_, eigvecF_, B, n, k1)
}

GamLoopGLOO <- function(beta_, Activeset, gamm, Y, Z, jj, jjfull, jjcomp, eps, YMean2, ZMean2, k, pk, M2f_, eigvalF_, eigvecF_, k1) {
    .Call('BigVAR_GamLoopGLOO', PACKAGE = 'BigVAR', beta_, Activeset, gamm, Y, Z, jj, jjfull, jjcomp, eps, YMean2, ZMean2, k, pk, M2f_, eigvalF_, eigvecF_, k1)
}

GamLoopSGLOO <- function(beta_, Activeset_, gamm, alpha, Y, Z, jj_, jjfull_, jjcomp_, eps, YMean2, ZMean2, k1, pk, M2f_, eigs_, m) {
    .Call('BigVAR_GamLoopSGLOO', PACKAGE = 'BigVAR', beta_, Activeset_, gamm, alpha, Y, Z, jj_, jjfull_, jjcomp_, eps, YMean2, ZMean2, k1, pk, M2f_, eigs_, m)
}

proxcpp <- function(v2, L, lambda, k, w) {
    .Call('BigVAR_proxcpp', PACKAGE = 'BigVAR', v2, L, lambda, k, w)
}

Fistapar <- function(Y, Z, phi, L, lambda, vsubs_, eps, tk, k) {
    .Call('BigVAR_Fistapar', PACKAGE = 'BigVAR', Y, Z, phi, L, lambda, vsubs_, eps, tk, k)
}

gamloopHVAR <- function(beta_, Y, Z, gammgrid, eps, YMean2, ZMean2, B1, k, p, vsubs_) {
    .Call('BigVAR_gamloopHVAR', PACKAGE = 'BigVAR', beta_, Y, Z, gammgrid, eps, YMean2, ZMean2, B1, k, p, vsubs_)
}

proxcppOO <- function(v2, L, lambda, vsubs, k, w) {
    .Call('BigVAR_proxcppOO', PACKAGE = 'BigVAR', v2, L, lambda, vsubs, k, w)
}

FistaOO <- function(Y, Z, phi, p, k, lambda, groups_, eps, tk, w) {
    .Call('BigVAR_FistaOO', PACKAGE = 'BigVAR', Y, Z, phi, p, k, lambda, groups_, eps, tk, w)
}

gamloopOO <- function(beta_, Y, Z, gammgrid, eps, YMean2, ZMean2, B1, k, p, w, groups_) {
    .Call('BigVAR_gamloopOO', PACKAGE = 'BigVAR', beta_, Y, Z, gammgrid, eps, YMean2, ZMean2, B1, k, p, w, groups_)
}

FistaElem <- function(Y, Z, phi, p, k, lambda, eps, tk) {
    .Call('BigVAR_FistaElem', PACKAGE = 'BigVAR', Y, Z, phi, p, k, lambda, eps, tk)
}

gamloopElem <- function(beta_, Y, Z, gammgrid, eps, YMean2, ZMean2, B1, k, p) {
    .Call('BigVAR_gamloopElem', PACKAGE = 'BigVAR', beta_, Y, Z, gammgrid, eps, YMean2, ZMean2, B1, k, p)
}

powermethod <- function(A, x1) {
    .Call('BigVAR_powermethod', PACKAGE = 'BigVAR', A, x1)
}

norm2 <- function(x) {
    .Call('BigVAR_norm2', PACKAGE = 'BigVAR', x)
}

gamloopHVARDL <- function(beta_, Y, Z, gammgrid_, eps, YMean2, ZMean2, k, p, vsubs_, gran2) {
    .Call('BigVAR_gamloopHVARDL', PACKAGE = 'BigVAR', beta_, Y, Z, gammgrid_, eps, YMean2, ZMean2, k, p, vsubs_, gran2)
}

HLassoVAR <- function(betaL_, Y, Z, gamm_, eps, k, p, groups, gran2) {
    .Call('BigVAR_HLassoVAR', PACKAGE = 'BigVAR', betaL_, Y, Z, gamm_, eps, k, p, groups, gran2)
}

HVARCVAL <- function(beta_, Zfull_, gamm_, eps, T0, T1, p, k, Z2, gran2, groups) {
    .Call('BigVAR_HVARCVAL', PACKAGE = 'BigVAR', beta_, Zfull_, gamm_, eps, T0, T1, p, k, Z2, gran2, groups)
}

HVAREval <- function(beta_, Zfull_, gamm_, eps, T1, T2, p, k, Z2, gran2, groups) {
    .Call('BigVAR_HVAREval', PACKAGE = 'BigVAR', beta_, Zfull_, gamm_, eps, T1, T2, p, k, Z2, gran2, groups)
}

RelaxedLS <- function(K, B2, k, p, k1, s) {
    .Call('BigVAR_RelaxedLS', PACKAGE = 'BigVAR', K, B2, k, p, k1, s)
}

ARFit <- function(K2, k, p) {
    .Call('BigVAR_ARFit', PACKAGE = 'BigVAR', K2, k, p)
}

Zmat1 <- function(Y, p, k) {
    .Call('BigVAR_Zmat1', PACKAGE = 'BigVAR', Y, p, k)
}

AIC <- function(Y, k, pmax) {
    .Call('BigVAR_AIC', PACKAGE = 'BigVAR', Y, k, pmax)
}

BIC <- function(Y, k, pmax) {
    .Call('BigVAR_BIC', PACKAGE = 'BigVAR', Y, k, pmax)
}

EvalIC <- function(Y, T1, k, pmax, IC) {
    .Call('BigVAR_EvalIC', PACKAGE = 'BigVAR', Y, T1, k, pmax, IC)
}

QRCons <- function(Z, T, k, B2, R2, p) {
    .Call('BigVAR_QRCons', PACKAGE = 'BigVAR', Z, T, k, B2, R2, p)
}

GamLoopSGLX <- function(beta_, Activeset, gamm, alpha, Y1, Z1, jj, jjfull, jjcomp, eps, YMean2, ZMean2, k, pk, M2f_, eigs, k1) {
    .Call('BigVAR_GamLoopSGLX', PACKAGE = 'BigVAR', beta_, Activeset, gamm, alpha, Y1, Z1, jj, jjfull, jjcomp, eps, YMean2, ZMean2, k, pk, M2f_, eigs, k1)
}

proxvx2 <- function(v2, L, lambda, m, k, F1) {
    .Call('BigVAR_proxvx2', PACKAGE = 'BigVAR', v2, L, lambda, m, k, F1)
}

GamLoopSGL <- function(beta_, Activeset, gamm, alpha, Y1, Z1, jj, jjfull, jjcomp, eps, YMean2, ZMean2, k, pk, M1f_, M2f_, eigs_) {
    .Call('BigVAR_GamLoopSGL', PACKAGE = 'BigVAR', beta_, Activeset, gamm, alpha, Y1, Z1, jj, jjfull, jjcomp, eps, YMean2, ZMean2, k, pk, M1f_, M2f_, eigs_)
}

